
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - JWT_KEY=secret

before_script:
  - psql -c 'create database wayfarer-test;' -U postgres

script:
  - npm test
after_success:
  - npm run coverage

notifications:
  email: false