
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

env:
  global:
  - JWT_KEY=secret

script:
  - npm test
after_success:
  - npm run coverage
notifications:
  email: false